# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='人名')),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='卡号')),
                ('bank_name', models.CharField(max_length=30, verbose_name='银行名字')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('authors', models.ManyToManyField(to='dj02apppuls.Author', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('life', models.IntegerField(verbose_name='职业生涯')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='语言名字')),
                ('desc', models.CharField(max_length=255, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='人名')),
                ('age', models.IntegerField()),
                ('bankcard', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dj02apppuls.BankCard', verbose_name='银行卡')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj02apppuls.Language', verbose_name='掌握的语言'),
        ),
    ]
